from enum import Enum


class Permission(str, Enum):
    ADMIN = "ADMIN"

    READ_ROLE = "READ_ROLE"
    CREATE_ROLE = "CREATE_ROLE"
    UPDATE_ROLE = "UPDATE_ROLE"
    DELETE_ROLE = "DELETE_ROLE"

    READ_USER = "READ_USER"
    UPDATE_USER = "UPDATE_USER"
    DELETE_USER = "DELETE_USER"
    BAN_USER = "BAN_USER"

    READ_CHARACTER = "READ_CHARACTER"
    UPDATE_CHARACTER = "UPDATE_CHARACTER"
    DELETE_CHARACTER = "DELETE_CHARACTER"
